# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --repo
script:
- set -o pipefail && xcodebuild test -workspace Theater.xcworkspace -scheme Theater -destination "platform=iOS Simulator,OS=14.0,name=iPhone SE" -enableCodeCoverage YES | xcpretty
- pod lib lint --allow-warnings
