sudo: required

before_install:
  - gem install cocoapods -v '1.1.0.beta.1'

osx_image: xcode7.3
language: objective-c

xcode_workspace: Actors.xcworkspace
xcode_scheme: Theater
xcode_sdk: iphonesimulator9.3
